#!/bin/sh
#
# Configure options script for re-calling GraphicsMagick compilation
# options required to use the GraphicsMagick library.
#
# Concept derived from gtk-config in the Gtk package except that Autoconf-style
# configuration information is presented instead so that it may be used more
# effectively in configure scripts.
#
usage='Usage: GraphicsMagick-config [--cflags] [--cppflags] [--exec-prefix] [--ldflags] [--libs] [--prefix] [--version]

 For example, "example.c" may be compiled to produce "example" as follows:

  "gcc -o example example.c `GraphicsMagick-config --cppflags --cflags --ldflags --libs`"'

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case $1 in
    --prefix)
      echo /usr/local/src/GRAPHICSMAGICK/1.3.18/graphicsmagick_build/graphicsmagick/1.3.18
      ;;
    --exec-prefix)
      echo /usr/local/src/GRAPHICSMAGICK/1.3.18/graphicsmagick_build/graphicsmagick/1.3.18
      ;;
    --version)
      echo 1.3.18
      ;;
    --cflags)
      echo '-fopenmp -g -O2 -Wall -pthread'
      ;;
    --cppflags)
      echo '-I/usr/local/src/GRAPHICSMAGICK/1.3.18/graphicsmagick_build/graphicsmagick/1.3.18/include/GraphicsMagick'
      ;;
    --ldflags)
      echo '-L/usr/local/src/GRAPHICSMAGICK/1.3.18/graphicsmagick_build/graphicsmagick/1.3.18/lib -L/usr/lib'
      ;;
    --libs)
      echo '-lGraphicsMagick -lfreetype -ljpeg -lpng12 -lXext -lSM -lICE -lX11 -lz -lm -lgomp -lpthread'
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done

