# Generated by CMake 2.8.8

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" GREATER 2.4)
  # Information for CMake 2.6 and above.
  SET("teem_LIB_DEPENDS" "general;/home/kitware/Dashboards/Package/Slicer-422-package/VTK-build/bin/libvtkzlib.so;general;/home/kitware/Dashboards/Package/Slicer-422-package/VTK-build/bin/libvtkpng.so;general;/home/kitware/Dashboards/Package/Slicer-422-package/VTK-build/bin/libvtkzlib.so;general;-lm;")
ELSE("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" GREATER 2.4)
  # Information for CMake 2.4 and lower.
  SET("teem_LIB_DEPENDS" "/home/kitware/Dashboards/Package/Slicer-422-package/VTK-build/bin/libvtkzlib.so;/home/kitware/Dashboards/Package/Slicer-422-package/VTK-build/bin/libvtkpng.so;/home/kitware/Dashboards/Package/Slicer-422-package/VTK-build/bin/libvtkzlib.so;-lm;")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" GREATER 2.4)
